name: Node.js build and lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 12.x, 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: sudo npm install -g yarn
      - name: Yarn
        run: yarn
        working-directory: webusb_site
      - run: yarn build --report
        working-directory: webusb_site
      - run: yarn lint
        working-directory: webusb_site
        env:
          CI: true
